### ISSUE TITLE
Failed prop type: Invalid prop `lote.artista` of type `object` supplied to `FirebaseConnect(withRouter(LoteForm))`, expected `string`.

### ISSUE THREAD

**Issue by varffs** [interglobalvision/admin-andamiaje-co#32]
![screen shot 2018-02-05 at 22 16 12](https://user-images.githubusercontent.com/845186/35831615-38cd8a4a-0ac2-11e8-9a13-84c4d8523538.png)

**Comment by mikeyrayvon** [comment]
i think this is probably fixed already? not sure how to recreate issue

**Comment by mixcas** [comment]
this is fixed
