### ISSUE TITLE
Unsaved deleted images get stuck

### ISSUE THREAD

**Issue by varffs** [interglobalvision/admin-andamiaje-co#76]
If you delete an image in an editor but don't save that post the reference is still saved on the post but points to nothing. You can then not delete the reference as the delete function errors when the target is not found.

**Comment by mixcas** [comment]
I think we should trigger update/create post on upload and deletion

**Comment by varffs** [comment]
I would agree. Only issue might be if someone did something weird like created a new post, uploaded an image before anything like title etc. Then closed the post without saving and were left with basically a weird draft version. However this is easy to fix so perhaps fine.
